### ISSUE TITLE
Minting breaks if Allowlist has more than 15 wallets

### ISSUE THREAD

**Issue by RocKhalil** [eliagoris/pnfts-mint#2]
Hey,
If you have more than 15 wallets, the instruction gets big and it breaks. Any idea how to fix it ?

**Comment by edceds** [comment]
@RocKhalil Yeah, a way to solve this is by using the [`signAllTransactions`](https://solana-labs.github.io/wallet-adapter/interfaces/_solana_wallet_adapter_react.WalletContextState.html#signAllTransactions) function through the `useWallet` hook, to build as many txs as necessary. Ping me on Discord, and I'm able to help: eliagoris#2665

**Comment by edceds** [comment]
#5
