### ISSUE TITLE
Impossible to mint guard groups

### ISSUE THREAD

**Issue by cicoph** [eliagoris/pnfts-mint#6]
Hi, any suggestion how to fix mint when use guards groups with pNFT?

**Comment by edceds** [comment]
Hi, currently there's no configuration, but you can use it by sending the group `label` as a parameter [here](https://github.com/eliagoris/pnfts-mint/blob/main/pages/index.tsx#L79). You can see that [this function](https://github.com/eliagoris/pnfts-mint/blob/main/utils/mintV2.ts#L64) accepts the group label

Ping me on Discord if you need further support eliagoris#2665
